apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: jp-test
  region: us-west-2
  tags:
    Namespace: Customer-Success
    Owner: justin.pflueger@fermyon.com
nodeGroups:
  - name: ng1-amazon-linux2
    amiFamily: AmazonLinux2
    instanceType: m5.large
    minSize: 1
    maxSize: 3
    desiredCapacity: 1
  - name: ng2-ubuntu-2004
    amiFamily: Ubuntu2004
    instanceType: m5.large
    minSize: 1
    maxSize: 3
    desiredCapacity: 1
