name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build-and-push-arm64:
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    env:
      SHIM_VERSION: 0.6.0
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate commit tag
      run: echo "GITHUB_SHA_SHORT=$(git rev-parse --short=6 \"$GITHUB_SHA\")" >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./image
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/${{ GITHUB_REPOSITORY }}:${{ SHIM_VERSION }}
          ghcr.io/${{ GITHUB_REPOSITORY }}:${{ SHIM_VERSION }}-${{ }}
        args: --build-arg SHIM_VERSION=${{ SHIM_VERSION }}

    - name: clear docker creds
      if: always()
      run: |
        rm -f ${HOME}/.docker/config.json